Update scripts

diff --git a/Scripts/find-gpu-firmware b/Scripts/find-gpu-firmware
--- a/Scripts/find-gpu-firmware
+++ b/Scripts/find-gpu-firmware
@@ -1,6 +1,16 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-# Function to colorize text and get corresponding firmware directory
+# SPDX-License-Identifier: BSD-3-Clause
+# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>
+
+
+# -- Exit on errors.
+
+set -e
+
+
+# -- Function to colorize text and get corresponding firmware directory.
+
 colorize() {
     local color=""
     local firmware_dir=""
@@ -30,13 +40,11 @@ colorize() {
     echo "$firmware_dir"
 }
 
-# Function to match pattern in the firmware directory
 match_pattern() {
     local pattern="$1"
     local firmware_dir="$2"
     local matched_items=()
 
-    # Use find command to match the pattern in the firmware directory
     while IFS= read -r -d '' item; do
         matched_items+=("$item")
     done < <(find "$firmware_dir" -type d -iname "*$pattern*" -print0)
@@ -55,40 +63,49 @@ match_pattern() {
 }
 
 
-# Run lshw with display class and store the result in a temporary file
+# -- Run lshw with display class and store the result in a temporary file.
+
 lshw -C display > lshw_output.txt
 
-# Get the number of display devices
+
+# -- Get the number of display devices.
+
 num_devices=$(grep -c "display" lshw_output.txt)
 
-# Iterate over each display device
+# -- Iterate over each display device.
+
 for ((i=0; i<num_devices; i++)); do
     echo "Display Device $((i+1)):"
     echo "-------------------"
 
-    # Extract vendor, product, bus info, and driver for the current device
+    # -- Extract vendor, product, bus info, and driver for the current device.
     vendor=$(awk -F': ' '/vendor:/{print $2}' lshw_output.txt | sed -n "$((i+1))p")
     product=$(awk -F': ' '/product:/{print $2}' lshw_output.txt | sed -n "$((i+1))p" | awk '{print $1}' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
     businfo=$(awk -F': ' '/bus info:/{print $2}' lshw_output.txt | sed -n "$((i+1))p")
     driver=$(awk -v n=$((i+1)) -F': ' '/driver/{gsub(/^[ \t]+|latency=[0-9]+|driver=/,"",$2); if (++c==n) print $2}' lshw_output.txt)
 
-    # Colorize the vendor based on the specified conditions and get the corresponding firmware directory
+    # -- Colorize the vendor based on the specified conditions and get the corresponding firmware directory.
+
     vendor_and_color=$(colorize "$vendor" "$vendor")
     vendor="${vendor_and_color%$'\n'*}"
     firmware_dir="${vendor_and_color#*$'\n'}"
 
-    # Print the extracted information for the current device
+    # -- Print the extracted information for the current device.
+
     echo "Bus Info: $businfo"
     echo "Product: $product"
     echo "Vendor: $vendor"
     echo "Driver: $driver"
 
-    # Match the pattern in the firmware directory
+    # -- Match the pattern in the firmware directory.
+
     matched_item=$(match_pattern "$product" "$firmware_dir")
     echo "Matched Item: $matched_item"
 
     echo
 done
 
-# Remove the temporary file
+
+# -- Remove the temporary file.
+
 rm lshw_output.txt
diff --git a/Scripts/unbind-vga b/Scripts/unbind-vga
--- a/Scripts/unbind-vga
+++ b/Scripts/unbind-vga
@@ -1,4 +1,14 @@
-#! /bin/bash
+#!/usr/bin/env bash
+
+# SPDX-License-Identifier: BSD-3-Clause
+# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>
+
+
+# -- Exit on errors.
+
+set -e
+
+
 # shellcheck disable=SC2034
 PREREQS=""
 
